version: '3.1'

services:
  ugap-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ugap-api-node-modules:/opt/npm
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
      # node inspect port
      - "9229:9229"
    depends_on:
      - mongo
      - createbuckets
    environment:
      NODE_PORT: 3000

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myAccessKey
      MINIO_ROOT_PASSWORD: mySecretKey

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 myAccessKey mySecretKey;
      /usr/bin/mc mb myminio/ugap;
      /usr/bin/mc policy set download myminio/ugap;
      exit 0;
      "

volumes:
  mongo-data:
  ugap-api-node-modules:
  minio-data:
