openapi: 3.0.0
info:
  description: |
    Nova Upload Service reference documentation.
  version: 1.0.0
  title: Nova Upload Service documentation

servers:
  - url: http://localhost:3000
    description: Local Server
  - url: https://api.qa.fireboltconnect.com
    description: QA Firebolt Connect
    
tags:
  - name: "Identity API"
  - name: "Sign Document (RALA)"
  - name: "Upload API"
  - name: "Warehouse API"

security:
  - JWT: []

paths:

  # /users
  /admin/users:
    post:
      $ref: "./endpoints/users/createUser.yml"

  /admin/users/me:
    get:
      $ref: "./endpoints/users/getUserInfo.yml"
    patch:
      $ref: "./endpoints/users/updateUserInfo.yml"
  /admin/users/validate:
    get:
      $ref: "./endpoints/users/validateUser.yml"
  /admin/users/requestresetpassword:
    post:
      $ref: "./endpoints/users/requestResetPassword.yml"
  /admin/users/resetpassword:
    post:
      $ref: "./endpoints/users/resetPassword.yml"

  # /login
  /admin/login:
    post:
      $ref: "./endpoints/users/loginUser.yml"

  # /signeddocuments
  /admin/signeddocuments:
    post:
      $ref: "./endpoints/sign-document/createDocument.yml"
    get:
      $ref: "./endpoints/sign-document/getDocument.yml"
  /admin/signeddocuments/sign:
    post:
      $ref: "./endpoints/sign-document/signDocument.yml"

  # applications
  /admin/applications:
    post:
      $ref: "./endpoints/applications/createApplication.yml"
    get:
      $ref: "./endpoints/applications/listApplications.yml"
  /admin/applications/{applicationId}:
    parameters:
    - name: applicationId
      in: path
      required: true
      description: The ID of the application to retrieve
      schema:
        type: string
    get:
      $ref: "./endpoints/applications/getApplication.yml"
    put:
      $ref: "./endpoints/applications/updateApplication.yml"
    delete:
      $ref: "./endpoints/applications/deleteApplication.yml"
  /admin/applications/{applicationId}/restore:
    parameters:
    - name: applicationId
      in: path
      required: true
      description: The ID of the application to retrieve
      schema:
        type: string
    patch:
      $ref: "./endpoints/applications/restoreApplication.yml"

  # application versions
  /admin/applications/{applicationId}/versions:
    parameters:
    - name: applicationId
      in: path
      required: true
      description: The ID of the application to retrieve
      schema:
        type: string
    post:
      $ref: "./endpoints/application-versions/createVersion.yml"
    get:
      $ref: "./endpoints/application-versions/listVersions.yml"
  /admin/applications/{applicationId}/versions/{versionId}:
    parameters:
    - name: applicationId
      in: path
      required: true
      description: The ID of the application to retrieve
      schema:
        type: string
    - name: versionId
      in: path
      required: true
      description: The ID of the application version to retrieve
      schema:
        type: string
    get:
      $ref: "./endpoints/application-versions/getVersion.yml"
    put:
      $ref: "./endpoints/application-versions/updateVersion.yml"
    delete:
      $ref: "./endpoints/application-versions/deleteVersion.yml"
  /admin/applications/{applicationId}/versions/{versionId}/restore:
    parameters:
    - name: applicationId
      in: path
      required: true
      description: The ID of the application to retrieve
      schema:
        type: string
    - name: versionId
      in: path
      required: true
      description: The ID of the application version to retrieve
      schema:
        type: string
    patch:
      $ref: "./endpoints/application-versions/restoreVersion.yml"
  /admin/applications/{applicationId}/versions/{versionId}/upload:
      parameters:
      - name: applicationId
        in: path
        required: true
        description: The ID of the application to retrieve
        schema:
          type: string
      - name: versionId
        in: path
        required: true
        description: The ID of the application version to retrieve
        schema:
          type: string
      post:
        $ref: "./endpoints/application-versions/uploadVersion.yml"
components:
  securitySchemes:
    JWT: # Login required
      type: http
      scheme: bearer
      bearerFormat: JWT
