# Application API

## Variables
# @host=http://localhost:3000
@host=http://nova.us-east-2.elasticbeanstalk.com
@application_id = 6542b9e43f2495872e109b3a
@version_id = 6542bae73f2495872e109b46
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDJiOTNlM2YyNDk1ODcyZTEwOWIzMyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY5ODg3MTYxNCwiZXhwIjoxNjk5MDQ0NDE0fQ.FST71CR1gtqEAd0NS8829lJFsQktElyFyHGQ6yIAXFk

### Create an application version

POST {{host}}/admin/applications/{{application_id}}/versions HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "version": "0.1.1",
  "changelog": "Fixed the bugs related to routes"
}


### List all applications versions

GET {{host}}/admin/applications/{{application_id}}/versions HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Get application version details

GET {{host}}/admin/applications/{{application_id}}/versions/{{version_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Update application version details

PUT {{host}}/admin/applications/{{application_id}}/versions/{{version_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "changelog": "Fixing a typo in my changelog"
}

### Upload application version

POST {{host}}/admin/applications/{{application_id}}/versions/{{version_id}}/upload HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="blitsSampleApp.zip"
Content-Type: application/zip

< ./blitsSampleApp.zip
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete application version

DELETE {{host}}/admin/applications/{{application_id}}/versions/{{version_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Restore application

PATCH {{host}}/admin/applications/{{application_id}}/versions/{{version_id}}/restore HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

