# Application API

## Variables
# @host=http://localhost:3000
@host=http://nova.us-east-2.elasticbeanstalk.com
@application_id = 6542f3bd2bbf4b78507a2cd0
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDJiOTNlM2YyNDk1ODcyZTEwOWIzMyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY5ODg3MTYxNCwiZXhwIjoxNjk5MDQ0NDE0fQ.FST71CR1gtqEAd0NS8829lJFsQktElyFyHGQ6yIAXFk

### Create an application

POST {{host}}/admin/applications/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Sample App",
  "identifier": "sample-app"
}


### List all applications

GET {{host}}/admin/applications/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Get application details

GET {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Update application

PUT {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "status": "active"
}

### Delete application

DELETE {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


### Restore application

PATCH {{host}}/admin/applications/{{application_id}}/restore HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
