# Application API

## Variables
@host=http://localhost:3000
@application_id = 64db28ffde5e19f81f035c1f
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGIxOGVkMTZiYWIyOGMwNzgwODA0MSIsImVtYWlsIjoidGVzdDNAdGVzdC5jb20iLCJpYXQiOjE2OTIwODAzNjUsImV4cCI6MTY5MjA5MTE2NX0.DZBq5OXqBvgh9sVLLP--J3tqCqd6rIL09ITc991wnVM

### Create an application

POST {{host}}/admin/applications/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test name",
  "identifier": "test identifier3"
}


### List all applications

GET {{host}}/admin/applications/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Get application details

GET {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Update application

PUT {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "location": "location bla"
}

### Delete application

DELETE {{host}}/admin/applications/{{application_id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


### Restore application

PATCH {{host}}/admin/applications/{{application_id}}/restore HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
