# Authentication API

## Variables
@email=test@test.com
@password=Welcome123!
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxZmM2ODU0MTM4MmJkMzNlOGUzYiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTY4OTk2NTgwMywiZXhwIjoxNjg5OTc2NjAzfQ.m9JK75DewufMSRJwqP2W5prDu7I6k07491GrjDLpERo

### Login

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Register

POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Retrieve user info

GET http://localhost:3000/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Update user info

PATCH http://localhost:3000/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "foo@bar.com",
}
