# Authentication API

## Variables
# @host=http://localhost:3000
@host=http://nova.us-east-2.elasticbeanstalk.com
@email=test@example.com
@password=Welcome123!
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDJiOTNlM2YyNDk1ODcyZTEwOWIzMyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY5ODg3MTYxNCwiZXhwIjoxNjk5MDQ0NDE0fQ.FST71CR1gtqEAd0NS8829lJFsQktElyFyHGQ6yIAXFk

### Login

POST {{host}}/admin/login HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Register

POST {{host}}/admin/users/ HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Retrieve user info

GET {{host}}/admin/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Update user info

PATCH {{host}}/admin/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "foo@bar.com",
  "password": "{{password}}"
}
