# Application API

## Variables
@application_id = 64db28ffde5e19f81f035c1f


### List all applications

GET http://localhost:3000/applications/ HTTP/1.1
content-type: application/json

### List all applications with minimal formatter

GET http://localhost:3000/applications?format=minimal HTTP/1.1
content-type: application/json

### Get application details

GET http://localhost:3000/applications/{{application_id}} HTTP/1.1
content-type: application/json


### Get application version details

GET http://localhost:3000/applications/{{application_id}}/versions/{{version_id}} HTTP/1.1
content-type: application/json
