# Application API

## Variables
@host=http://localhost:3000

# Application ID and Version ID variables contain dummy values, used
# only for running local tests. They are not associated with any real
# application
@application_id = 6542b9e43f2495872e109b3a
@version_id = 6542bae73f2495872e109b46

### List all applications

GET {{host}}/applications/ HTTP/1.1
content-type: application/json

### List all applications with minimal formatter

GET {{host}}/applications?format=minimal HTTP/1.1
content-type: application/json

### List all applications with non-existing formatter (should use default instead)

GET {{host}}/applications?format=nothing HTTP/1.1
content-type: application/json

### Get application details

GET {{host}}/applications/{{application_id}} HTTP/1.1
content-type: application/json

### Get application details with minimal formatter

GET {{host}}/applications/{{application_id}}?format=minimal HTTP/1.1
content-type: application/json


### Get application version details

GET {{host}}/applications/{{application_id}}/versions/{{version_id}} HTTP/1.1
content-type: application/json
