### Signed Document

## Variables
# @host=http://localhost:3000
@host=http://localhost:3000
@documentId=88c72871f6ac1c0f5f13ce03
@userId=1234567890
@firstname=john
@lastname=johnson
@title=coo
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDJiOTNlM2YyNDk1ODcyZTEwOWIzMyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY5ODg3MTYxNCwiZXhwIjoxNjk5MDQ0NDE0fQ.FST71CR1gtqEAd0NS8829lJFsQktElyFyHGQ6yIAXFk

GET   {{host}}/admin/signeddocument HTTP/1.1
content-type: application/json

{
  "id": "{{{{documentId}}}}",
}

POST  {{host}}/admin/signeddocument HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "content": "Lorum Ipsum ......",
  "type": "rala",
  "version": "1.0.0"
}

POST  {{host}}/admin/signeddocument/sign HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "ralaId": "{{{{documentId}}}}",
  "firstname": "{{firstname}}",
  "lastname": "{{lastname}}",
  "title": "{{title}}",
}
