tags:
- Applications
summary: "Deletes an application"
description: "Deletes an application"
operationId: "deleteApplication"
security:
  - JWT: [user]
responses:
  200:
    description: "Application is deleted"
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
              enum: ['success', 'error']
              default: 'success'
              description: Status for overall request
  400:
    $ref: "../../errors/http400.yml"
  401:
    $ref: "../../errors/http401.yml"
  404:
    $ref: "../../errors/http404.yml"
