name: Integration Tests

on:
  - pull_request

jobs:
  vitest-integration:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          JWT_VALID_FOR: ${{ vars.JWT_VALID_FOR }}
          JWT_SHORT_VALID_FOR: ${{ vars.JWT_SHORT_VALID_FOR }}
          PASSWORD_VALID_FOR: ${{ vars.PASSWORD_VALID_FOR }}
          OTP_VALID_FOR: ${{ vars.OTP_VALID_FOR }}

      - name: "Report Coverage"
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
